# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision/SetTrackingColours.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SetTrackingColours(genpy.Message):
  _md5sum = "2c86efe874e740a21108c4cdc260ae8a"
  _type = "vision/SetTrackingColours"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 hue_low
uint8 hue_high
uint8 sat_low
uint8 sat_high
uint8 val_low
uint8 val_high

"""
  __slots__ = ['hue_low','hue_high','sat_low','sat_high','val_low','val_high']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hue_low,hue_high,sat_low,sat_high,val_low,val_high

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetTrackingColours, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.hue_low is None:
        self.hue_low = 0
      if self.hue_high is None:
        self.hue_high = 0
      if self.sat_low is None:
        self.sat_low = 0
      if self.sat_high is None:
        self.sat_high = 0
      if self.val_low is None:
        self.val_low = 0
      if self.val_high is None:
        self.val_high = 0
    else:
      self.hue_low = 0
      self.hue_high = 0
      self.sat_low = 0
      self.sat_high = 0
      self.val_low = 0
      self.val_high = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6B().pack(_x.hue_low, _x.hue_high, _x.sat_low, _x.sat_high, _x.val_low, _x.val_high))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.hue_low, _x.hue_high, _x.sat_low, _x.sat_high, _x.val_low, _x.val_high,) = _get_struct_6B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6B().pack(_x.hue_low, _x.hue_high, _x.sat_low, _x.sat_high, _x.val_low, _x.val_high))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.hue_low, _x.hue_high, _x.sat_low, _x.sat_high, _x.val_low, _x.val_high,) = _get_struct_6B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6B = None
def _get_struct_6B():
    global _struct_6B
    if _struct_6B is None:
        _struct_6B = struct.Struct("<6B")
    return _struct_6B
