# Config file for PhantomX Reactor

port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AI05UUQJ-if00-port0
read_rate: 15
write_rate: 25

joints: {
    arm_1_joint: {id: 1, neutral: 205, max_angle: 180, min_angle: -60, max_speed: 30},
    arm_2_joint: {id: 2, max_angle: -90, min_angle: 90, max_speed: 30},
    arm_2_1_joint: {id: 3, max_angle: 90, min_angle: -90, max_speed: 30},
    arm_3_joint: {id: 4, max_angle: -90, min_angle: 90, max_speed: 30},
    arm_3_1_joint: {id: 5, max_angle: 90, min_angle: -90, max_speed: 30},
    arm_4_joint: {id: 6, max_angle: 100, min_angle: 80, max_speed: 30},
    arm_gripper_joint: {id: 8, max_speed: 30.0, range: 180, min_angle: -90.0, max_angle: 90.0},
}

